### ISSUE TITLE
OpenFile dialog?

### ISSUE THREAD

**Issue by hopewise** [SempaiGames/extension-nativedialog#1]
How about OpenFile dialog ?!

**Comment by fbricker** [comment]
Hi, most probably we'll be adding File Dialigs and some other in the future. But for now, you may want to take a look at: https://github.com/waneck/systools or https://github.com/mlabbe/nativefiledialog

Thanks!

**Comment by hopewise** [comment]
Thanks

On Tue, Oct 27, 2015 at 10:05 PM, Federico Bricker <notifications@github.com

> wrote:
> 
> Hi, most probably we'll be adding File Dialigs and some other in the
> future. But for now, you may want to take a look at:
> https://github.com/waneck/systools or
> https://github.com/mlabbe/nativefiledialog
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SempaiGames/extension-nativedialog/issues/1#issuecomment-151611894
> .

## 

## 

## Kind Regards,

Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East
